sonar.projectKey=siddur
sonar.projectName=siddur
sonar.projectVersion=0.1.0

sonar.sources=docs,context
sonar.exclusions=**/__pycache__/**,**/*.pyc,output/**

sonar.python.coverage.reportPaths=coverage.xml

sonar.python.bandit.reportPaths=reports/bandit.json
sonar.python.flake8.reportPaths=reports/flake8.txt
sonar.python.mypy.reportPaths=reports/mypy.txt
sonar.python.pylint.reportPaths=reports/pylint.txt
sonar.python.ruff.reportPaths=reports/ruff.json
